### PR TITLE
#76 the key is guiding the creation of the list of recipients

### PR DESCRIPTION
**Pull request by sanastasiadis**
Instead of checking if the recipient's name exists in the key, just get all the entries of the key (semicolon separated), and search to find them in the general list of recipients

### CODE REVIEW

**Comment by bbottema** [comment]
This breaks the parsing of the "simple reply with CC.msg" test message, tested in `HighoverEmailsTest.testToCcBcc()`. In this test case, it doesn't find all CC addresses anymore with this change.

**Comment by sanastasiadis** [comment]
Sorry for this, I made a correction and I executed the tests to confirm that they pass.

**Comment by bbottema** [comment]
Hi!

> Instead of checking if the recipient's name exists in the key, just get all the entries of the key (semicolon separated), and search to find them in the general list of recipients

Can you please tell me which problem this solves? Do you have an Outlook message that doesn't parse properly without this change? Thanks!

**Comment by sanastasiadis** [comment]
This resolves the issue #76, and as an example the given file in the issue can be used (CC duplicate recipients bug.msg).

There is a "to" recipient with the same name with a "cc" recipient (with different email addresses though).

The current code, after parsing, the list of getToRecipients returns both _OutlookRecipient's_, and the list of _getCcRecipients_ returns also both _OutlookRecipient's_. Which is wrong.

The fix returns only one _OutlookRecipient_ for the _getToRecipients_ and only one _OutlookRecipient_ for the _getCcRecipients_, however it is not guaranteed that it will return the correct one with the correct address (one is returned with the correct address, and the other with the wrong address), thus it is resolved **partially**.

To highlight the issue, I added one more msg file (test subject duplicated recipients.msg) which contains **exactly** the same recipient as "to" and as "cc" recipient.
The current code returns twice the same _OutlookRecipient_ for both _getToRecipients_ and _getCcRecipients_.
In this case, both the number of the recipients list, the names and the addresses are corrected with the fix.

**Comment by bbottema** [comment]
Unfortunately, this doesn't completely solve the bug yet. The number of recipients are correct, but the actual recipient addresses are switched up (TO becomes CC and CC becomes TO).

See branch [bug_duplicate_recipients](https://github.com/bbottema/outlook-message-parser/tree/bug_duplicate_recipients) for a proper test case, [`HighoverEmailsTest.testDuplicateRecipientsBug`](https://github.com/bbottema/outlook-message-parser/blob/97069f8b4222a841a30fd0f3944f9041ea248f1b/src/test/java/org/simplejavamail/outlookmessageparser/HighoverEmailsTest.java#L76). As you can see, it still fails when I merge your changes into it. Could you have a look please?

**Comment by bbottema** [comment]
Closing as invalid problem/solution. I'm happy to reopen if this is addressed.

**Pull request closed without merging**
