### PR TITLE
Adding possibility to parse X500 Names

### PR DESCRIPTION
**Pull request by dwlabcube**
this is a possible fix for the Issue from "Recipient as Exchange Member will throw Exception emailAddressList is required #477" in the Java Simple Mail Repo.

### CODE REVIEW

**Comment by bbottema** [comment]
Released in 1.10.0

**Comment by dwlabcube** [comment]
i am so sorry. i have put it on the wrong lines before. now i have created a new pill request. again, i am so sorry. #68

**Comment by bbottema** [comment]
No biggy, the change wasn't harmful anyway, and you caught it quickly. Thanks for helping out!

**Comment by bbottema** [comment]
1.10.1 released!

**Comment by bbottema** [comment]
Updated in 1.10.2 for better detection

**Pull request merged**
