### PR TITLE
Issue 43 use javax.mail to extract Date: and From: from the HEADERS

### PR DESCRIPTION
**Pull request by basinilya**

### CODE REVIEW

**Comment by basinilya** [comment]
@bbottema 

> making this library fail for half of the users

Do you mean some problem with Java 9+? Will moving to jakarta solve the problem? I didn't know that it was a complete replacement.

> Is this a deliberate choice?

No. I just copied the dependency from another project.

**Comment by bbottema** [comment]
> @bbottema
> 
> > making this library fail for half of the users
> 
> Do you mean some problem with Java 9+? Will moving to Jakarta solve the problem? I didn't know that it was a complete replacement.

No, the choice for either JavaMail or Jakarta Mail should be with the user; if we choose, we cut out half of the library users. So if possible even with extra effort, outlook-message-parser should do without either of these frameworks.

**Comment by basinilya** [comment]
In this case let's copy and refactor jakarta classes to your package

**Comment by bbottema** [comment]
I merged this into master with a fix to both the Maven license and SpotBugs plugins to ignore these included 3rd party code. I want a junit test that demonstrates the added value of your code (test case for the bug it solves).

**Comment by bbottema** [comment]
Junit test added, case closed. Will release soon...

**Pull request merged**
